[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"

[healthcheck]
path = "/"
timeout = 30
